"""
pre_build.py — PlatformIO pre-build hook
Runs automatically before every compile/upload.

Detects this machine's current LAN IP, reads PORT from .env,
then writes include/config.h with the correct server URLs.
sketch.ino includes config.h instead of hardcoding anything.

NOTE: `Import` and `env` are SCons builtins injected by PlatformIO at
build time. Linters (Pyrefly, Pylance) will flag them as unknown — that
is expected and harmless. The try/except below keeps linters quiet.
"""

import os
import re
import socket


# ----------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------

def get_local_ip() -> str:
    """
    Returns the machine's outbound LAN IP by connecting a UDP socket
    to an external address (no data is actually sent).
    Falls back to 127.0.0.1 if the network is unavailable.
    """
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "127.0.0.1"


def get_port_from_env(project_dir: str) -> int:
    """Reads PORT from the .env file if present, otherwise returns 3000."""
    env_path = os.path.join(project_dir, ".env")
    if not os.path.exists(env_path):
        return 3000
    with open(env_path) as f:
        for line in f:
            m = re.match(r"^\s*PORT\s*=\s*(\d+)", line)
            if m:
                return int(m.group(1))
    return 3000


def generate_config(pio_env) -> None:  # type: ignore[no-untyped-def]
    """Generates include/config.h with the current server IP and port."""
    project_dir: str = pio_env.get("PROJECT_DIR")

    ip   = get_local_ip()
    port = get_port_from_env(project_dir)
    base = f"http://{ip}:{port}"

    config_h = f"""\
// ============================================================
// AUTO-GENERATED by pre_build.py — DO NOT EDIT MANUALLY
// Re-generated on every PlatformIO build with the current
// server machine IP.  Edit pre_build.py to change behaviour.
// ============================================================
#pragma once

#define KIOSK_SERVER_HOST  "{base}"
#define KIOSK_API_URL      "{base}/api/hardware/event"
#define KIOSK_STATUS_URL   "{base}/api/hardware/status"
"""

    include_dir = os.path.join(project_dir, "include")
    os.makedirs(include_dir, exist_ok=True)

    config_path = os.path.join(include_dir, "config.h")
    with open(config_path, "w") as f:
        f.write(config_h)

    print(f"\n[pre_build] Server IP detected : {ip}")
    print(f"[pre_build] Port (from .env)    : {port}")
    print(f"[pre_build] Generated config.h  : {base}\n")


# ----------------------------------------------------------------
# PlatformIO entry point
# `Import` and `env` are SCons builtins — only available when this
# script is executed by PlatformIO, not by a standalone Python run.
# ----------------------------------------------------------------
try:
    Import("env")        # type: ignore[name-defined]
    generate_config(env) # type: ignore[name-defined]
except NameError:
    # Running outside PlatformIO (e.g. linter, direct python call) — skip.
    pass
